#!/usr/bin/env python3
"""Embed a Vela-optimised TFLite file in the RA8P1 firmware."""

from __future__ import annotations

import argparse
from pathlib import Path


def format_bytes(data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    model = args.input.read_bytes()
    source = f"""\
/*
 * Embedded YOLO-Fastest COCO80 model compiled for Ethos-U55-256.
 * Upstream wrapper and integration files identify the model as Apache-2.0.
 * Generated by tools/embed_tflite.py; do not edit by hand.
 */

#include <cstddef>
#include <cstdint>

namespace arm
{{
namespace app
{{
namespace object_detection
{{
extern const int originalImageSize = 320;
extern const int channelsImageDisplayed = 3;
extern const float anchor1[] = {{12.0F, 18.0F, 37.0F, 49.0F, 52.0F, 132.0F}};
extern const float anchor2[] = {{115.0F, 73.0F, 119.0F, 199.0F, 242.0F, 238.0F}};

alignas(16) static const uint8_t nn_model[] =
{{
{format_bytes(model)}
}};

uint8_t const * GetModelPointer()
{{
    return nn_model;
}}

size_t GetModelLen()
{{
    return sizeof(nn_model);
}}
}} /* namespace object_detection */
}} /* namespace app */
}} /* namespace arm */
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source, encoding="ascii", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
